//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Lib_SQM_Domain.dev145 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SQM_AccountServiceSoap", Namespace="http://icm051/")]
    public partial class SQM_AccountService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SP_CreateAccountOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SQM_AccountService() {
            this.Url = global::Lib_SQM_Domain.Properties.Settings.Default.Lib_SQM_Domain_dev145_SQM_AccountService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SP_CreateAccountCompletedEventHandler SP_CreateAccountCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://icm051/SP_CreateAccount", RequestNamespace="http://icm051/", ResponseNamespace="http://icm051/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SP_CreateAccount(string AuthorizedID, string AuthorizedPassword, string NewUserID, string NewUserPassword, string RoleID, string Mail) {
            object[] results = this.Invoke("SP_CreateAccount", new object[] {
                        AuthorizedID,
                        AuthorizedPassword,
                        NewUserID,
                        NewUserPassword,
                        RoleID,
                        Mail});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SP_CreateAccountAsync(string AuthorizedID, string AuthorizedPassword, string NewUserID, string NewUserPassword, string RoleID, string Mail) {
            this.SP_CreateAccountAsync(AuthorizedID, AuthorizedPassword, NewUserID, NewUserPassword, RoleID, Mail, null);
        }
        
        /// <remarks/>
        public void SP_CreateAccountAsync(string AuthorizedID, string AuthorizedPassword, string NewUserID, string NewUserPassword, string RoleID, string Mail, object userState) {
            if ((this.SP_CreateAccountOperationCompleted == null)) {
                this.SP_CreateAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSP_CreateAccountOperationCompleted);
            }
            this.InvokeAsync("SP_CreateAccount", new object[] {
                        AuthorizedID,
                        AuthorizedPassword,
                        NewUserID,
                        NewUserPassword,
                        RoleID,
                        Mail}, this.SP_CreateAccountOperationCompleted, userState);
        }
        
        private void OnSP_CreateAccountOperationCompleted(object arg) {
            if ((this.SP_CreateAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SP_CreateAccountCompleted(this, new SP_CreateAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void SP_CreateAccountCompletedEventHandler(object sender, SP_CreateAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SP_CreateAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SP_CreateAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591